### ISSUE TITLE
How does sext affect match_object/select on non-key?

### ISSUE THREAD

**Issue by vans163** [aeternity/mnesia_rocksdb#7]
Would performance suffer compared to normal mnesia disk copies for match_object and selects on non-key objects? 

For example if I have
```elixir
[
{143, %{user_type: :client}}
{145, %{user_type: :client}}
{153, %{user_type: :admin}}
] = :ets.tab2list(tab)
:mnesia.dirty_match_object(tab, {:_, %{user_type: :client}})
```

Would this be significantly slower as it would have to deserialize every term?

**Comment by uwiger** [comment]
That would have to be compared to `dets` (`disc_only_copies`) then.

For both `dets` and `rocksdb` or `leveldb` tables, `select` and `match_object` on non-key patterns will have to traverse the whole table and decode each object into internal Erlang representation. Just comparing `sext` and the built-in decode of the external term format, the latter is of course much more efficient, partly because it's C code vs Erlang but also because the external term format is a tighter encoding – thus fewer bytes to process. But for relatively small objects, the difference shouldn't be significant.

Essentially, `dets` will be superior to `rocksdb` or `leveldb` in cases where:
(The table is small enough that `dets` will perform well – or indeed at all [1],
AND
(You don't need ordered_set semantics,
AND/OR
You don't need efficient partial-key matching))

[1] At least based on benchmarks some years ago, I wouldn't recommend `dets` for tables larger than 1 GB, even if one stays well away from the hard 2 GB limit.

**Comment by vans163** [comment]
I am simply addicted to match_object and selects to an extent.   I wonder if there's a way to get rocks_db to play nice with that on non-keys.

**Comment by tolbrino** [comment]
I think this topic deserves some benchmarks before to understand the divide. Feel free to submit a PR with those.
